### ISSUE TITLE
Failed to respawn on death.

### ISSUE THREAD

**Issue by Beldantazar** [Daivuk/apdoom#6]
### Background

Version of Crispy Doom: Archipelago 1.0.3

Operating System and version: Windows 11

Game: (Doom/Heretic/Hexen/Strife/other) Doom 1993

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:  When I died as part of a multiworld game (reset level on death was enabled) it did not reset the level on death at all and I just stayed dead.  I was unable to trigger a respawn and had to release all items to allow the other players to proceed.  

Expected behavior: For the game to reset the level as described on the options.

**Comment by Daivuk** [comment]
Just to confirm I've seen this. Been reported often. Never was able to repro this. I would love a save file + apworld zip + user when this happens. If quitting and reloading doesnt fix it, that save file I could use to add a fix.

**Comment by VorpalStorm** [comment]
This happened to me just recently. Daivuk, lemme know exactly what files you want to examine and I can send them over.

**Comment by Wryyyong** [comment]
> Just to confirm I've seen this. Been reported often. Never was able to repro this. I would love a save file + apworld zip + user when this happens. If quitting and reloading doesnt fix it, that save file I could use to add a fix.

Here, instance that just happened to me -- contains `apstate.json` and all DSG files for the run up to that point, user is "Wryyyong": [AP_W70925506325953290800_57727979796F6E67.zip](https://github.com/user-attachments/files/16242585/AP_W70925506325953290800_57727979796F6E67.zip)

A small workaround as well, until this is fixed:
1. Exit out of APDOOM entirely
2. In the APDOOM directory, enter the subdirectory for the bugged multi-world run (eg. in my case, it was `AP_W70925506325953290800_57727979796F6E67`)
3. Open `apstate.json` in your text editor of choice
4. Edit JSON node `.player.health` to any value between `0` and `200`, and save the file.
5. Re-launch APDOOM with your credentials for the bugged multi-world run and enter the game.

At this state, the player should now _not_ be in a bugged death state (can lose health, can interact with objects and demons, etc.), but your weapons will still be bugged for the current level. To fix this, just open the pause menu and select 'Kill' (or just die again) to properly reset the level and player state, and the issue should be resolved.

**Comment by KScl** [comment]
All instances of this bug should be resolved by 1.2.0 already
