### ISSUE TITLE
Frequent Crashes on Mt. Erebus

### ISSUE THREAD

**Issue by Yrcrazypa** [Daivuk/apdoom#7]
### Background

Version of Crispy Doom: 1.0.3

Operating System and version: Windows 10

Game: (Doom/Heretic/Hexen/Strife/other) Doom 1993

Any loaded WADs and mods (please include full command line): Archipelago Multiworld

### Bug description

Observed behavior: Frequent Crashes at random in Mt. Erebus (E3M6) Can't tell what specifically triggers it.

Expected behavior: Not crashing.

**Comment by Daivuk** [comment]
I would have needed a save + apworld zip. I played apdoom countless time and never crashed on that map. Could be something very specific, but without reproductible files I can't fix this.
