### ISSUE TITLE
Enhancement: Update to archipelago.gg setup guide for Doom 1993 to include experimental working Linux configuration setup

### ISSUE THREAD

**Issue by beatsgo** [Daivuk/apdoom#8]
### Background

Version of Crispy Doom: APDoom 1.0.3 / Crispy Doom 6.0.0

Operating System and version: ArchLinux (Kernel version 6.6.10-arch1-1)

Game: Doom 1993

Any loaded WADs and mods (please include full command line): None

#### Observed behavior:
![apdoom_linux](https://github.com/Daivuk/apdoom/assets/20424816/4ed4fb9e-0fd1-48d9-a97a-f7ac1b58f1a2)
- Able to deploy an instance of APDoom through Wine 8.0.2
- Had to uninstall Mono and install Dot Net Framework 4.8 in the Wine Prefix.
  - Determined Mono for whatever reason does not handle websocket request correctly through APCpp.dll
  - [Official Steps](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38203)
  - [Inspiration for determining solution](https://eden-daoc.net/viewtopic.php?p=414&sid=d2b28c08840d90c351906fcc42ff4ae7#p414 )
- Tested in an Archipelago room instance with success.
- Validated with a friend they were able to connect.

#### Suggested for Linux setup section:
- *Support for Linux is not available, thus these steps are experimental and does not guarantee 100% functionality. These steps assumes user has some type of command line knowledge to utilize Wine with APDoom. In addition, each distro/flavor of Linux has different versions/packages; please review distro specific package software manager documentation for installation guidelines.
- Additional prerequisite software:
  - Wine
  - Winetricks
- Uninstall mono ([Source](https://forum.winehq.org/viewtopic.php?p=140762&sid=11b3ab14db4dee4a211e585bfc533498#p140762))
```
 wine uninstaller --list
 wine uninstaller --remove {47A1FA26-B71E-5325-8161-20CF885181FF}
 wine uninstaller --remove {7426CCE2-5341-534D-BAB0-1DAEDCCE76CE}
```
- Install latest DotNet Framework 4.8 ([Source](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38203))
```
winetricks --force dotnet40 corefonts
```
- Install VCRun2022
```
winetricks --force vcrun2022
```
- Follow rest of the steps below with few noted differences.
  - Place APDoom extracted files in "~/.wine/drive_c" folder
  - Launch APDoom with the following command:
```
wine ~/.wine/drive_c/APDoom/apdoom-launcher.exe
```
##### Expected behavior:
- Guide only shows Windows native configuration.

**Comment by Daivuk** [comment]
Thanks for this, will add to the documentation.
But I think it should go into APDOOM documentation and maybe not directly on ap.gg? It's a client app issue.

**Comment by beatsgo** [comment]
- That is true, consistency would be nice between APDoom's documentation and the Archipelago's website. But that's not exactly my call which I do understand from your end this is more client app side to avoid ambiguity overall. 
- Additionally, I will also convey this enhancement in the documentation should work with Doom 2 and theoretically with Heretic. In another AP session, one of my acquaintances who was in it were able to successfully run Doom 2 on a Linux machine with the above mentioned instructions. 
- Lastly, additional note for custom prefixes should be added if someone decides to run this in a dedicated WINE folder structure.
- With that I shall update this enhancement for clarity.

**Comment by Daivuk** [comment]
You can go ahead and add this to the README file, or create a separate one (Linked from main) if you feel that's cleaner.
Then put up a PR.

**Comment by KScl** [comment]
I'm sure you're aware of this already, since we share a discord server, but I'm going to be handling native Linux builds going forward; no need to mess with WINE any longer.
